@file:JvmName("ArbZipKt")
@file:JvmMultifileClass

package com.tegonal.variist.generators

/**
 * Zips `this` [ArbArgsGenerator] with the given [other]&nbsp;[ArbArgsGenerator], [transform]ing
 * the pairwise generated values of type [A1] and [A2] to type [R].
 *
 * @param other The other [ArbArgsGenerator] which generates values of type [A2].
 * @param transform The transformation function which takes an [A1] and [A2] and produces an [R].
 *
 * @param A1 The type of values generated by `this` [ArbArgsGenerator].
 * @param A2 The type of values generated by the given [other]&nbsp;[ArbArgsGenerator].
 * @param R the type of values generated by the resulting [ArbArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
//TODO 2.1.0 add ordered.zip as well, which has size = minOf(this.size, other.size)
fun <A1, A2, R> ArbArgsGenerator<A1>.zip(
	other: ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): ArbArgsGenerator<R> = transform { seq, seedOffset ->
	seq.zip(other.generate(this._core.seedBaseOffset + 1 + seedOffset), transform)
}

