package com.tegonal.variist.generators

import com.tegonal.variist.config._components
import com.tegonal.variist.generators.impl.IntFromUntilArbArgsGenerator

/**
 * Turns `this` [SemiOrderedArgsGenerator] into an [ArbArgsGenerator].
 *
 * @param T The type of values generated by `this` [OrderedArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator].
 *
 * @since 2.0.0
 */
fun <T> SemiOrderedArgsGenerator<T>.toArbArgsGenerator(): ArbArgsGenerator<T> =
	IntFromUntilArbArgsGenerator(
		_components,
		seedBaseOffset = 0,
		from = 0,
		toExclusive = size
	).map { offset -> this.generateOne(offset) }
