@file:JvmName("ArbZipKt")
@file:JvmMultifileClass

package com.tegonal.minimalist.generators

/**
 * Combines `this` [ArbArgsGenerator] with the given [other] [ArbArgsGenerator], [ArbArgsGenerator.transform]ing
 * the pairwise generated values of type [A1] and [A2] to type [R] with the help of the given [transform] function.
 *
 * @param other The other [ArbArgsGenerator] which generates values of type [A2].
 * @param transform The transformation function which takes an [A1] and [A2] and produces an [R].
 *
 * @param A1 The type of values generated by `this` [ArbArgsGenerator].
 * @param A2 The type of values generated by the given [other] [ArbArgsGenerator].
 * @param R the type of values generated by the resulting [ArbArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> ArbArgsGenerator<A1>.zip(
	other: ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): ArbArgsGenerator<R> = transform { seq, seedOffset ->
	seq.zip(other.generate(this._core.seedBaseOffset + 1 + seedOffset), transform)
}

