package com.tegonal.minimalist.generators

import com.tegonal.minimalist.config.IsComponentFactoryContainerProvider

/**
 * Represents a generator which generates [T]s.
 *
 * @param T the type of values generated by `this` [ArgsGenerator].
 *
 * @since 2.0.0
 */
interface ArgsGenerator<out T> : IsComponentFactoryContainerProvider
