package com.tegonal.minimalist.generators

import com.tegonal.minimalist.config._components
import com.tegonal.minimalist.generators.impl.IntFromUntilArbArgsGenerator

/**
 * Represents an [ArgsGenerator] which provides the method [generate] which generates [T]s always in the same
 * order and a finite number ([size]) before repeating.
 *
 * @since 2.0.0
 */
interface OrderedArgsGenerator<out T> : SemiOrderedArgsGenerator<T> {

	/**
	 * Returns the maximum of values `this` generator is able to generate before it starts over again.
	 *
	 * @since 2.0.0
	 */
	override val size: Int

	/**
	 * Returns an infinite stream of values starting at [offset] and repeating after reaching [size] of values
	 * where always the same values are generated when called multiple times.
	 *
	 * @since 2.0.0
	 */
	override fun generate(offset: Int): Sequence<T>


	/**
	 * Turns `this` [OrderedArgsGenerator] into an [ArbArgsGenerator].
	 *
	 * @param T The type of values generated by `this` [OrderedArgsGenerator].
	 *
	 * @return The resulting [ArbArgsGenerator].
	 *
	 * @since 2.0.0
	 */
	//TODO 2.0.0 move up to SemiOrderedArgsGenerator?
	fun toArbArgsGenerator(): ArbArgsGenerator<T> =
		IntFromUntilArbArgsGenerator(
			_components,
			seedBaseOffset = 0,
			from = 0,
			toExclusive = size
		).map { offset -> this.generate(offset).first() }
}

