package com.tegonal.minimalist.generators

import com.tegonal.minimalist.generators.impl.OrderedToRandomArgsGenerator

/**
 * Turns `this` [OrderedArgsGenerator] into a [RandomArgsGenerator].
 *
 * @param T The type of values generated by `this` [OrderedArgsGenerator].
 *
 * @return The resulting [RandomArgsGenerator].
 *
 * @since 2.0.0
 */
fun <T> OrderedArgsGenerator<T>.toRandomArgsGenerator(): RandomArgsGenerator<T> =
	OrderedToRandomArgsGenerator(this)

