package com.tegonal.minimalist.generators

import ch.tutteli.kbox.Tuple2
import com.tegonal.minimalist.config._components
import com.tegonal.minimalist.config.ordered

/**
 * Generates [size][OrderedArgsGenerator.size] values, creates another [OrderedArgsGenerator] per value
 * with the help of the given [otherFactory], materialises this other generator as well and combines its values with
 * the corresponding value of `this` generator into a [Tuple2].
 *
 * @param otherFactory Builds an [OrderedArgsGenerator] based on a given value of type [A1].
 *
 * @param A1 The type of values generated by `this` [OrderedArgsGenerator].
 * @param A2 The type of values generated by the given [OrderedArgsGenerator] (built by the given [otherFactory]).
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [Tuple2]`<A1, A2>`.
 *
 * @since 2.0.0
 */
fun <A1, A2> OrderedArgsGenerator<A1>.combineDependentMaterialised(
	otherFactory: OrderedExtensionPoint.(A1) -> OrderedArgsGenerator<A2>,
): OrderedArgsGenerator<Tuple2<A1, A2>> = combineDependentMaterialised(otherFactory, ::Tuple2)


/**
 * Generates [size][OrderedArgsGenerator.size] values, creates another [OrderedArgsGenerator] per value
 * with the help of the given [otherFactory], materialises this other generator as well and combines its values with
 * the corresponding value of `this` generator with the help of the given [transform] function to type [R].
 *
 * @param otherFactory Builds an [OrderedArgsGenerator] based on a given value of type [A1].
 * @param transform The transformation function which takes an [A1] and [A2] and produces an [R].
 *
 * @param A1 The type of values generated by `this` [OrderedArgsGenerator].
 * @param A2 The type of values generated by the given [OrderedArgsGenerator] (built by the given [otherFactory]).
 * @param R the type of values generated by the resulting [OrderedArgsGenerator].
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> OrderedArgsGenerator<A1>.combineDependentMaterialised(
	otherFactory: OrderedExtensionPoint.(A1) -> OrderedArgsGenerator<A2>,
	transform: (A1, A2) -> R
): OrderedArgsGenerator<R> = transformMaterialised { seq ->
	seq.flatMap { a1 ->
		val otherGenerator = this._components.ordered.otherFactory(a1)
		otherGenerator.generate().take(otherGenerator.size).map { a2 ->
			transform(a1, a2)
		}
	}
}
