package com.tegonal.minimalist.generators

/**
 * Represents an [ArgsGenerator] which provides [generate] which generates [T]s an infinite number of times in a random
 * or not defined order.
 *
 * @param T the type of values generated by `this` [RandomArgsGenerator].
 *
 * @since 2.0.0
 */
interface RandomArgsGenerator<out T> : ArgsGenerator<T> {

	/**
	 * Generates an infinite stream of random values of type [T].
	 * @since 2.0.0
	 */
	fun generate(): Sequence<T>
}
