package com.tegonal.minimalist.generators

/**
 * Represents an [ArgsGenerator] which provides [generate] which generates [T]s an infinite number of times in a random
 * or not defined order.
 *
 * @param T the type of values generated by `this` [RandomArgsGenerator].
 *
 * @since 2.0.0
 */
// TODO 2.1.0 introduce something like RandomArgsSizeAwareGenerator which has a size and
//  provides a way to turn itself into an OrderedArgsGenerator. This would be useful for small spaces as we could just
//  return all values in case an ArgsRangeDecider decides to take more then the available size
interface RandomArgsGenerator<out T> : ArgsGenerator<T> {

	/**
	 * Generates an infinite stream of random values of type [T].
	 * @since 2.0.0
	 */
	fun generate(): Sequence<T>
}
