@file:JvmName("SemiOrderedZipKt")
@file:JvmMultifileClass

package com.tegonal.minimalist.generators

import com.tegonal.minimalist.generators.impl.SemiOrderedZipArbArgsGenerator

/**
 * Combines `this` [SemiOrderedArgsGenerator] with the given [other]&nbsp;[ArbArgsGenerator] and [transform]s the generated
 * values pairwise, returning a [SemiOrderedArgsGenerator] which generates values of type [R].
 *
 * The resulting [SemiOrderedArgsGenerator] still generates [this.size][SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param other The other [ArbArgsGenerator] which generates values of type [A2].
 * @param A1 The type of values generated by `this` [OrderedArgsGenerator].
 * @param A2 the type of values generated by the [other]&nbsp;[OrderedArgsGenerator].
 * @param R the type of values generated by the resulting [OrderedArgsGenerator].
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.zip(
	other: ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = SemiOrderedZipArbArgsGenerator(this, other, transform)
