@file:JvmName("SemiOrderedCombineDependentKt")
@file:JvmMultifileClass
package com.tegonal.minimalist.generators

import com.tegonal.minimalist.config._components
import com.tegonal.minimalist.config.arb


/**
 * Creates for each generated value of type [A1] by `this` [SemiOrderedArgsGenerator] another [SemiOrderedArgsGenerator]
 * with the help of the given [otherFactory] where the other generator generates values of type [A2] and then
 * [transform]s the value of `this` [SemiOrderedArgsGenerator] with one value of the other [ArbArgsGenerator] to type [R].
 *
 * @param otherFactory Builds an [ArbArgsGenerator] based on a given value of type [A1].
 * @param transform The transformation function which takes an [A1] and [A2] and produces an [R].
 *
 * @param A1 The type of values generated by `this` [SemiOrderedArgsGenerator].
 * @param A2 The type of values generated by the given [ArbArgsGenerator] (built by the given [otherFactory]).
 * @param R the type of values generated by the resulting [ArbArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator] which generates values of type [R].
 *
 * @return The resulting [ArbArgsGenerator] which generates [Pair]s of [A1] and [A2].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.combineDependent(
	otherFactory: ArbExtensionPoint.(A1) -> ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = mapIndexed { index, a1 ->
	transform(a1, this._components.arb.otherFactory(a1).generateOne(index))
}
