@file:JvmName("SemiOrderedArgsGeneratorCombineKt")
@file:JvmMultifileClass

package com.tegonal.minimalist.generators

import com.tegonal.minimalist.config._components
import com.tegonal.minimalist.config.arb
import com.tegonal.minimalist.generators.impl.SemiOrderedArgsGeneratorCombiner
import com.tegonal.minimalist.generators.impl.SemiOrderedWithArbArgsGeneratorCombiner
import com.tegonal.minimalist.generators.impl.throwUnsupportedArgsGenerator

/**
 * Combines `this` [SemiOrderedArgsGenerator] with the given [other] [SemiOrderedArgsGenerator] and [transform]s the generated
 * values pairwise, returning a [SemiOrderedArgsGenerator] which generates values of type [R].
 *
 * The resulting [SemiOrderedArgsGenerator] generates
 * [this.size][SemiOrderedArgsGenerator.size] * [other.size][SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param other The other [OrderedArgsGenerator] which generates values of type [A2].
 * @param A1 The type of values generated by `this` [OrderedArgsGenerator].
 * @param A2 the type of values generated by the [other] [OrderedArgsGenerator].
 * @param R the type of values generated by the resulting [OrderedArgsGenerator].
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.combine(
	other: SemiOrderedArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = SemiOrderedArgsGeneratorCombiner(this, other, transform)

/**
 * Combines `this` [SemiOrderedArgsGenerator] with the given [other] [ArbArgsGenerator] and [transform]s the generated
 * values pairwise, returning a [SemiOrderedArgsGenerator] which generates values of type [R].
 *
 * The resulting [SemiOrderedArgsGenerator] still generates [this.size][SemiOrderedArgsGenerator.size] values before repeating.
 *
 * @param other The other [ArbArgsGenerator] which generates values of type [A2].
 * @param A1 The type of values generated by `this` [OrderedArgsGenerator].
 * @param A2 the type of values generated by the [other] [OrderedArgsGenerator].
 * @param R the type of values generated by the resulting [OrderedArgsGenerator].
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.combine(
	other: ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = SemiOrderedWithArbArgsGeneratorCombiner(this, other, transform)


/**
 * Combines `this` [SemiOrderedArgsGenerator] with the given [other] [ArgsGenerator] and [transform]s the generated
 * values pairwise, returning a [SemiOrderedArgsGenerator] which generates values of type [R].
 *
 * It is not statically known what [SemiOrderedArgsGenerator.size] the resulting [SemiOrderedArgsGenerator] will have.
 *
 * @return The resulting [OrderedArgsGenerator] which generates values of type [R].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.combine(
	other: ArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = when (other) {
	is SemiOrderedArgsGenerator<A2> -> combine(other, transform)
	is ArbArgsGenerator<A2> -> combine(other, transform)
	else -> throwUnsupportedArgsGenerator(other)
}

/**
 * Creates for each generated value of type [A1] by `this` [SemiOrderedArgsGenerator] another [SemiOrderedArgsGenerator]
 * with the help of the given [otherFactory] where the other generator generates values of type [A2] and then
 * [transform]s the value of `this` [ArbArgsGenerator] with one value of the other [ArbArgsGenerator] to type [R].
 *
 * @param otherFactory Builds an [ArbArgsGenerator] based on a given value of type [A1].
 * @param transform The transformation function which takes an [A1] and [A2] and produces an [R].
 *
 * @param A1 The type of values generated by `this` [SemiOrderedArgsGenerator].
 * @param A2 The type of values generated by the given [ArbArgsGenerator] (built by the given [otherFactory]).
 * @param R the type of values generated by the resulting [ArbArgsGenerator].
 *
 * @return The resulting [ArbArgsGenerator] which generates values of type [R].
 *
 * @return The resulting [ArbArgsGenerator] which generates [Pair]s of [A1] and [A2].
 *
 * @since 2.0.0
 */
fun <A1, A2, R> SemiOrderedArgsGenerator<A1>.combineDependent(
	otherFactory: ArbExtensionPoint.(A1) -> ArbArgsGenerator<A2>,
	transform: (A1, A2) -> R
): SemiOrderedArgsGenerator<R> = this.mapIndexed { index, a1 ->
	transform(a1, this._components.arb.otherFactory(a1).generateOne(index))
}
