name: "Code Quality"
on: [push, pull_request]

jobs:
  before_pr:
    name: Bash Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install shellcheck v0.9.0
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: before-pr.sh
        run: ./scripts/before-pr.sh

  matrix_prep:
    name: Matrix Preparation Gradle
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          node .github/workflows/matrix.js

  gradle_build:
    needs: matrix_prep
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    name: '${{ matrix.name }}'
    env:
      JAVA_VERSION: ${{ matrix.java_version }}
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java_distribution }}
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: "build using jdk ${{ matrix.java_version }}"
        run: ./gradlew build

  # TODO integrate TODO-checker
