name: "Code Quality"
on: [push, pull_request]

jobs:
  Bash_Code_Quality:
    name: Bash Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install shellcheck v0.9.0
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: before-pr.sh
        run: ./scripts/before-pr.sh

  # TODO use https://github.com/vlsi/github-actions-random-matrix

  Gradle_Ubuntu:
    env:
      JAVA_VERSION: ${{ matrix.java_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        java_version: [ 11, 17 ]

    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
          cache: 'gradle'

      - name: "build using jdk ${{ matrix.java_version }}"
        run: ./gradlew build

  # TODO integrate TODO-checker
