name: Quality Assurance
on: [push, pull_request]

jobs:
  before_pr:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: before-pr.sh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: install shellcheck
        run: ./lib/tegonal-scripts/src/ci/install-shellcheck.sh
      - name: before-pr.sh
        run: ./scripts/before-pr.sh

  matrix_prep:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    name: Matrix Preparation gradle
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          node .github/workflows/matrix.js

  gradle_build:
    needs: matrix_prep
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    name: '${{ matrix.name }}'
    env:
      JAVA_VERSION: ${{ matrix.java_version }}
    steps:
      - uses: actions/checkout@v5
      - name: "Set up JDK ${{ matrix.java_version }}"
        uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.java_distribution }}
          java-version: ${{ matrix.java_version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: "build using jdk ${{ matrix.java_version }}"
        run: ./gradlew build
